const minutesAgo = (minutes) => new Date(Date.now() - minutes * 60 * 1000).toISOString();
const hoursAgo = (hours) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
const hoursFromNow = (hours) => new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
export const DEMO_POSTS = [
  {
    id: 'demo-feed-minyan-early',
    type: 'news',
    post_subtype: 'shul_update',
    title: 'Early Shacharis tomorrow: which minyan is most reliable?',
    body: 'Need to be on the LIRR by 7:18 from Cedarhurst. Is the 6:20 at YILC still ending on time, or is there a better Woodmere option?',
    author_name: 'Ari G.',
    user_id: 'local-demo',
    community_id: 'five-towns-shul-network',
    community_name: 'Five Towns Shul Network',
    city: 'Five Towns',
    location_text: 'Cedarhurst',
    created_date: minutesAgo(14),
    updated_date: new Date().toISOString(),
    likes_count: 18,
    comments_count: 16,
  },
  {
    id: 'demo-feed-meals',
    type: 'help',
    post_subtype: 'chesed',
    title: 'Two Shabbos meal deliveries still open',
    body: 'One family in Woodmere and one in Lawrence need prepared meals dropped off before 1:30 Friday. Can split it if two people are available.',
    author_name: 'Rachel B.',
    user_id: 'local-demo-2',
    community_id: 'chesed-response-circle',
    community_name: 'Chesed Response Circle',
    city: 'Five Towns',
    location_text: 'Woodmere',
    created_date: minutesAgo(31),
    updated_date: new Date().toISOString(),
    likes_count: 27,
    comments_count: 12,
  },
  {
    id: 'demo-feed-restaurant',
    type: 'feed',
    post_subtype: 'recommendation',
    title: 'Best place for a quiet business lunch on Central?',
    body: 'Need kosher, not too loud, and decent seating for 3 people around 1 PM. Bonus if parking is not impossible.',
    author_name: 'Mordy K.',
    user_id: 'local-demo-3',
    community_id: 'jewish-marketplace-fivetowns',
    community_name: 'Five Towns Jewish Marketplace',
    city: 'Five Towns',
    location_text: 'Cedarhurst',
    created_date: minutesAgo(47),
    updated_date: new Date().toISOString(),
    likes_count: 9,
    comments_count: 23,
  },
  {
    id: 'demo-feed-event-tonight',
    type: 'event',
    post_subtype: 'local_event',
    title: 'Women’s shiur and dessert tonight',
    body: '8:15 PM in Woodmere. Topic is keeping connection at the Shabbos table with teens. Anyone know if there is a Zoom option?',
    author_name: 'Tova G.',
    user_id: 'local-demo-4',
    community_id: 'simcha-events-board',
    community_name: 'Simcha & Events Board',
    city: 'Five Towns',
    location_text: 'Woodmere',
    created_date: hoursAgo(1.2),
    updated_date: new Date().toISOString(),
    event_date: hoursFromNow(7),
    likes_count: 33,
    comments_count: 18,
  },
  {
    id: 'demo-feed-lost-siddur',
    type: 'feed',
    post_subtype: 'lost_found',
    title: 'Lost and found: black leather siddur',
    body: 'Found near Central Ave after mincha. Name inside looks like “Y. Rosen” but hard to read. I can leave it by the shul office.',
    author_name: 'Shul Office',
    user_id: 'local-demo-5',
    community_id: 'five-towns-shul-network',
    community_name: 'Five Towns Shul Network',
    city: 'Five Towns',
    location_text: 'Cedarhurst',
    created_date: hoursAgo(2),
    updated_date: new Date().toISOString(),
    likes_count: 14,
    comments_count: 7,
  },
  {
    id: 'demo-feed-halacha',
    type: 'news',
    post_subtype: 'learning',
    title: '20-minute halacha chabura after Maariv',
    body: 'Quick practical review: reheating soup, blech questions, and what to do if the urn was unplugged. Source sheet posted later tonight.',
    author_name: 'Rabbi Adler',
    user_id: 'local-demo-6',
    community_id: 'daily-learning-beis',
    community_name: 'Daily Learning Beis',
    city: 'Five Towns',
    location_text: 'Woodmere',
    created_date: hoursAgo(2.5),
    updated_date: new Date().toISOString(),
    likes_count: 41,
    comments_count: 11,
  },
  {
    id: 'demo-feed-jfk-ride',
    type: 'help',
    post_subtype: 'ride',
    title: 'JFK ride tomorrow 5:45 AM',
    body: 'One adult, one carry-on, leaving from Lawrence. Happy to pay gas or split with anyone already going that way.',
    author_name: 'Dani P.',
    user_id: 'local-demo-7',
    community_id: 'shabbos-table-hosts',
    community_name: 'Shabbos Table Hosts',
    city: 'Five Towns',
    location_text: 'Lawrence',
    created_date: hoursAgo(3),
    updated_date: new Date().toISOString(),
    likes_count: 7,
    comments_count: 14,
  },
  {
    id: 'demo-feed-park',
    type: 'event',
    post_subtype: 'parents',
    title: 'Parent meetup at Andrew J. Parise Park',
    body: 'A few families are meeting after school if the weather holds. Good for ages 3-7. Anyone bringing scooters?',
    author_name: 'Naomi A.',
    user_id: 'local-demo-8',
    community_id: 'young-parents-five-towns',
    community_name: 'Young Parents Five Towns',
    city: 'Five Towns',
    location_text: 'Cedarhurst',
    created_date: hoursAgo(4),
    updated_date: new Date().toISOString(),
    event_date: hoursFromNow(27),
    likes_count: 19,
    comments_count: 20,
  },
  {
    id: 'demo-feed-new-family',
    type: 'feed',
    post_subtype: 'welcome',
    title: 'New family moving to Inwood this week',
    body: 'Family with two kids under 6. Looking for someone to drop off a small welcome basket and maybe invite them for Shabbos lunch.',
    author_name: 'Welcome Committee',
    user_id: 'local-demo-9',
    community_id: 'five-towns-shul-network',
    community_name: 'Five Towns Shul Network',
    city: 'Five Towns',
    location_text: 'Inwood',
    created_date: hoursAgo(5),
    updated_date: new Date().toISOString(),
    likes_count: 22,
    comments_count: 10,
  },
  {
    id: 'demo-feed-hosting',
    type: 'help',
    post_subtype: 'shabbos',
    title: 'Two guests looking for Shabbos lunch',
    body: 'Newly married couple staying in Woodmere. Walking distance preferred. They are easygoing, no allergies.',
    author_name: 'Tova G.',
    user_id: 'local-demo-10',
    community_id: 'shabbos-table-hosts',
    community_name: 'Shabbos Table Hosts',
    city: 'Five Towns',
    location_text: 'Woodmere',
    created_date: hoursAgo(5.5),
    updated_date: new Date().toISOString(),
    likes_count: 35,
    comments_count: 17,
  },
  {
    id: 'demo-feed-pickleball',
    type: 'event',
    post_subtype: 'hobbies',
    title: 'Pickleball ladder needs two more players',
    body: 'Thursday 8:15 PM, beginner-friendly court and one competitive court. Please comment skill level so we can split evenly.',
    author_name: 'Josh M.',
    user_id: 'local-demo-11',
    community_id: 'five-towns-pickleball',
    community_name: 'Five Towns Pickleball & Sports',
    city: 'Five Towns',
    location_text: 'Lawrence',
    created_date: hoursAgo(6),
    updated_date: new Date().toISOString(),
    event_date: hoursFromNow(30),
    likes_count: 26,
    comments_count: 21,
  },
  {
    id: 'demo-feed-babysitter',
    type: 'feed',
    post_subtype: 'recommendation',
    title: 'Reliable Motzei Shabbos babysitter?',
    body: 'Looking for someone for 7:45-10:30 in Hewlett. Kids are asleep most of the time. Any names you trust?',
    author_name: 'Esti F.',
    user_id: 'local-demo-12',
    community_id: 'young-parents-five-towns',
    community_name: 'Young Parents Five Towns',
    city: 'Five Towns',
    location_text: 'Hewlett',
    created_date: hoursAgo(6.5),
    updated_date: new Date().toISOString(),
    likes_count: 12,
    comments_count: 28,
  },
  {
    id: 'demo-feed-marketplace-chairs',
    type: 'feed',
    post_subtype: 'marketplace',
    title: 'Looking to borrow 12 folding chairs',
    body: 'Need them for a small vort next Tuesday in Cedarhurst. Can pick up and return same night.',
    author_name: 'Yoni G.',
    user_id: 'local-demo-13',
    community_id: 'jewish-marketplace-fivetowns',
    community_name: 'Five Towns Jewish Marketplace',
    city: 'Five Towns',
    location_text: 'Cedarhurst',
    created_date: hoursAgo(7),
    updated_date: new Date().toISOString(),
    likes_count: 8,
    comments_count: 13,
  },
  {
    id: 'demo-feed-eruv',
    type: 'news',
    post_subtype: 'shul_update',
    title: 'Eruv status thread for this week',
    body: 'Can we keep one thread here for any updates? Please post only confirmed info and source.',
    author_name: 'Avi R.',
    user_id: 'local-demo-14',
    community_id: 'five-towns-shul-network',
    community_name: 'Five Towns Shul Network',
    city: 'Five Towns',
    location_text: 'Five Towns',
    created_date: hoursAgo(8),
    updated_date: new Date().toISOString(),
    likes_count: 44,
    comments_count: 19,
  },
  {
    id: 'demo-feed-seforim',
    type: 'feed',
    post_subtype: 'marketplace',
    title: 'Free seforim shelf pickup',
    body: 'A few duplicate Mishnayos sets and old chumashim available. Please take only what you will use.',
    author_name: 'Miriam C.',
    user_id: 'local-demo-15',
    community_id: 'jewish-marketplace-fivetowns',
    community_name: 'Five Towns Jewish Marketplace',
    city: 'Five Towns',
    location_text: 'Woodmere',
    created_date: hoursAgo(9),
    updated_date: new Date().toISOString(),
    likes_count: 31,
    comments_count: 15,
  },
  {
    id: 'demo-feed-tech',
    type: 'help',
    post_subtype: 'tech_help',
    title: 'Can someone help set up a printer for an older neighbor?',
    body: 'Near Peninsula Blvd. Probably 20 minutes if you know wireless printers. They are flexible tonight or tomorrow.',
    author_name: 'Moshe K.',
    user_id: 'local-demo-16',
    community_id: 'chesed-response-circle',
    community_name: 'Chesed Response Circle',
    city: 'Five Towns',
    location_text: 'Hewlett',
    created_date: hoursAgo(10),
    updated_date: new Date().toISOString(),
    likes_count: 16,
    comments_count: 8,
  },
  {
    id: 'demo-feed-singles',
    type: 'event',
    post_subtype: 'singles',
    title: 'Board game night: still room for 6',
    body: 'Moderated singles event Motzei Shabbos. Ages 24-32. Details sent after approval. Anyone able to bring Codenames?',
    author_name: 'Tamar K.',
    user_id: 'local-demo-17',
    community_id: 'jewish-singles-circle',
    community_name: 'Jewish Singles Circle',
    city: 'Five Towns',
    location_text: 'Nassau and Queens',
    created_date: hoursAgo(11),
    updated_date: new Date().toISOString(),
    event_date: hoursFromNow(50),
    likes_count: 18,
    comments_count: 12,
  },
  {
    id: 'demo-feed-screens',
    type: 'feed',
    post_subtype: 'values',
    title: 'Phones at the Shabbos table: what actually works?',
    body: 'We want a warmer table, not a fight every week. What boundaries have worked in your home with teens?',
    author_name: 'Maya R.',
    user_id: 'local-demo-18',
    community_id: 'modern-orthodox-home-builders',
    community_name: 'Modern Orthodox Home Builders',
    city: 'Five Towns',
    location_text: 'Five Towns',
    created_date: hoursAgo(12),
    updated_date: new Date().toISOString(),
    likes_count: 52,
    comments_count: 34,
  },
  {
    id: 'demo-feed-cleanup',
    type: 'event',
    post_subtype: 'neighborhood',
    title: 'Sunday neighborhood cleanup',
    body: 'Meeting 10:30 near Central Ave. Gloves and bags provided. Good chesed hours opportunity for teens.',
    author_name: 'Cedarhurst Board',
    user_id: 'local-demo-19',
    community_id: 'cedarhurst-neighborhood-watch',
    community_name: 'Cedarhurst Neighborhood Board',
    city: 'Five Towns',
    location_text: 'Cedarhurst',
    created_date: hoursAgo(13),
    updated_date: new Date().toISOString(),
    event_date: hoursFromNow(72),
    likes_count: 23,
    comments_count: 9,
  },
  {
    id: 'demo-feed-apartment',
    type: 'feed',
    post_subtype: 'housing',
    title: 'Young couple looking for basement apartment',
    body: 'Woodmere/Lawrence preferred, near shul if possible. Budget flexible for the right place. Please message leads.',
    author_name: 'Leah W.',
    user_id: 'local-demo-20',
    community_id: 'five-towns-shul-network',
    community_name: 'Five Towns Shul Network',
    city: 'Five Towns',
    location_text: 'Woodmere',
    created_date: hoursAgo(15),
    updated_date: new Date().toISOString(),
    likes_count: 10,
    comments_count: 18,
  },
  {
    id: 'demo-feed-tehillim',
    type: 'help',
    post_subtype: 'tehillim',
    title: 'Tehillim group tonight 9:15',
    body: 'Short call for a local refuah request. Please comment if you want the name privately.',
    author_name: 'Chesed Circle',
    user_id: 'local-demo-21',
    community_id: 'chesed-response-circle',
    community_name: 'Chesed Response Circle',
    city: 'Five Towns',
    location_text: 'Five Towns',
    created_date: hoursAgo(16),
    updated_date: new Date().toISOString(),
    likes_count: 37,
    comments_count: 22,
  },
  {
    id: 'demo-feed-carpool',
    type: 'help',
    post_subtype: 'ride',
    title: 'Cedarhurst to Woodmere morning carpool',
    body: 'We have two seats available leaving 7:48. Can add one stop near Central if timing works.',
    author_name: 'Ben T.',
    user_id: 'local-demo-22',
    community_id: 'young-parents-five-towns',
    community_name: 'Young Parents Five Towns',
    city: 'Five Towns',
    location_text: 'Cedarhurst',
    created_date: hoursAgo(18),
    updated_date: new Date().toISOString(),
    likes_count: 11,
    comments_count: 10,
  },
  {
    id: 'demo-feed-cholent',
    type: 'feed',
    post_subtype: 'recommendation',
    title: 'Best takeout cholent for a small kiddush?',
    body: 'Need enough for around 35 people. Looking for something reliable and not too salty. Any recent experiences?',
    author_name: 'Noam C.',
    user_id: 'local-demo-23',
    community_id: 'jewish-marketplace-fivetowns',
    community_name: 'Five Towns Jewish Marketplace',
    city: 'Five Towns',
    location_text: 'Lawrence',
    created_date: hoursAgo(20),
    updated_date: new Date().toISOString(),
    likes_count: 15,
    comments_count: 26,
  },
];
